server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-management
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/*

        - id: careplan-management
          uri: http://localhost:8082
          predicates:
            - Path=/api/careplan/*

        - id: clinic-management
          uri: http://localhost:8083
          predicates:
            - Path=/api/clinic/*

        - id: patient-management
          uri: http://localhost:8084
          predicates:
            - Path=/api/patient/*
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: info
        trace: info
