package com.vantuan.careplanmanagement.common.enums;

public enum DoseUnit {

    BUCCAL_BETWEEN_GUMS_AND_TEETH,
    CUTANEOUS_CREAM,
    OTIC_EAR_CANAL,
    OCULAR_EYE_DROPS,
    INTRAMUSCULAR,
    INTRAVENOUS,
    NASAL_INHALATION,
    CUTANEOUS_OINTMENT,
    ORAL_TABLETS,
    ORAL_CAPSULES,
    ORAL_DROPS,
    ORAL_LOZENGES,
    ORAL_SYRUP,
    CUTANEOUS_POWDER,
    SUBCUTANEOUS_INJECTION,
    TRANSDERMAL_PATCH,
    SUBLINGUAL_UNDER_TONGUE,
    SUPPOSITORY_RECTAL,
    SUPPOSITORY_VAGINAL;

}
