package com.vantuan.careplanmanagement.common.enums;

public enum Reaction {

    ABDOMINAL_CRAMPS,
    ANAPHYLAXIS,
    ANGIOEDEMA,
    BRONCHOSPASM,
    COUGH,
    DIARRHEA,
    DIFFICULTY_BREATHING,
    EYE_REDNESS,
    EYE_TEARING,
    FATIGUE,
    FLUSHING,
    GASTROINTESTINAL_UPSET,
    HEADACHES,
    HIVES_OR_RASH,
    HYPOTENSION,
    ITCHING,
    LOSS_OF_CONSCIOUSNESS,
    MENTAL_STATUS_CHANGE,
    MYALGIA,
    NASAL_CONGESTION,
    NAUSEA,
    RESPIRATORY_FAILURE,
    RUNNY_NOSE,
    SEIZURES,
    SHORTNESS_OF_BREATH,
    SNEEZING,
    SWELLING,
    THROAT_AND_MOUTH_SWELLING,
    VOICE_CHANGE,
    VOMITING,
    WHEEZING,
    OTHER;

}

